# Generated by Django 5.2.7 on 2025-10-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('avg_cpu_percent', models.FloatField()),
                ('avg_memory_gb', models.FloatField()),
                ('avg_disk_io_mb_s', models.FloatField()),
                ('avg_net_io_mb_s', models.FloatField()),
                ('duration_seconds', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
